import Head from "next/head";
import Image from "next/image";
import styles from "./page.module.css";
import Header from "@/components/Header";

export default async function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section className={styles.mainSection}>
          <p className={styles.mainIntro}>
            Gemmy Portfolio에서 포트폴리오를 간편하게 만들고 공유하세요
          </p>
          <div className={styles.mainCover}></div>
        </section>
        <div>
          <section className={styles.subSection}>
            <div className={styles.wrapper}>
              <div className={styles.subSectionContainer}>
                <div className={styles.subSectionCover}></div>
                <div className={styles.subSectionContents}>
                  <h3>이것은 타이틀 입니다.</h3>
                  <p>이것은 내용 입니다.</p>
                </div>
              </div>
            </div>
          </section>
          <section className={styles.subSection}>
            <div className={styles.wrapper}>
              <div className={styles.subSectionContainer}>
                <div className={styles.subSectionCover}></div>
                <div className={styles.subSectionContents}>
                  <h3>이것은 타이틀 입니다.</h3>
                  <p>이것은 내용 입니다.</p>
                </div>
              </div>
            </div>
          </section>
          <section className={styles.subSection}>
            <div className={styles.wrapper}>
              <div className={styles.subSectionContainer}>
                <div className={styles.subSectionCover}></div>
                <div className={styles.subSectionContents}>
                  <h3>이것은 타이틀 입니다.</h3>
                  <p>이것은 내용 입니다.</p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.wrapper}> &copy; Jammy Studio</div>
      </footer>
    </>
  );
}
